//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 07:00:53 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.soap.springboot.vkakarla.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vkakarla.springboot.soap.interfaces;
